name       : libgweather
version    : 3.36.0
release    : 24
source     :
    - https://download.gnome.org/sources/libgweather/3.36/libgweather-3.36.0.tar.xz : d2ffeec01788d03d1bbf35113fc2f054c6c3600721088f827bcc31e5c603a32d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true -Denable_vala=true
build      : |
    %ninja_build
install    : |
    %ninja_install
