name       : libgweather
version    : 3.24.0
release    : 16
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libgweather/3.24/libgweather-3.24.0.tar.xz : 1089b932205085add19e5e1b63361c0cff1a2c46a67ab2dded6dd2ca87bdfa3d
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations.
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static \
               --enable-locations-compression
build      : |
    %make
install    : |
    %make_install
