name       : libgweather
version    : 3.32.1
release    : 21
source     :
    - https://download.gnome.org/sources/libgweather/3.32/libgweather-3.32.1.tar.xz : 1c2218ed71230dd2c550ca4fd3dab53e2f2831d38982c213575f34e48d68e980
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true -Denable_vala=true
build      : |
    %ninja_build
install    : |
    %ninja_install
