name       : libgweather
version    : 4.2.0
release    : 31
source     :
    - https://download.gnome.org/sources/libgweather/4.2/libgweather-4.2.0.tar.xz : af8a812da0d8976a000e1d62572c256086a817323fbf35b066dbfdd8d2ca6203
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false -Denable_vala=true -Dsoup2=false
build      : |
    %ninja_build
install    : |
    %ninja_install
