name        : libgweather
version     : 3.18.1
release     : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgweather/3.18/libgweather-3.18.1.tar.xz : 94b2292f8f7616e2aa81b1516befd7b27682b20acecbd5d656b6954990ca7ad0
license     :
    - LGPL-2.0
summary     : The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps   :
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - vala
description : |
    The libgweather package is a library used to access weather information from online services for numerous locations.
setup      : |
    %configure --disable-static \
               --enable-locations-compression
build      : |
    %make
install    : |
    %make_install
