name       : libgweather
version    : 3.26.0
release    : 18
source     :
    - https://download.gnome.org/sources/libgweather/3.26/libgweather-3.26.0.tar.xz : 5b84badc0b3ecffff5db1bb9a7cc4dd4e400a8eb3f1282348f8ee6ba33626b6e
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations.
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static \
               --enable-locations-compression
build      : |
    %make
install    : |
    %make_install
